name: NPM - Build and test

on:
  push:
    branches:
      - main
    paths:
      - "cli/**"
  pull_request:
    branches:
      - main
    paths:
      - "cli/**"
  workflow_dispatch:

jobs:
  checks:
    name: "Check CLI code - NPM"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node 24
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install and build shared
        working-directory: shared
        run: | 
          npm install
          npm run build

      - name: Install and build backend
        working-directory: backend
        run: |
          npm install
          npm run build

      - name: Install and build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build


