name: NPM - Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: "Check CLI code - NPM"
    runs-on: web3pi

    steps:
      - uses: actions/checkout@v4

      - name: Check requirements
        run: |
          set -x
          bun --version
          pnpm --version
          npm --version
          node --version
          node-gyp --version
          corepack --version
          yarn --version

      - name: Install and build shared
        working-directory: shared
        run: |
          bun install
          bun run build

      - name: Install and build backend
        working-directory: backend
        run: |
          bun install
          bun run build

      - name: Install and build frontend
        working-directory: frontend
        run: |
          bun install
          bun run build


