name: NPM - Check source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  checks:
    name: "Check CLI code - NPM"
    runs-on: web3pi

    steps:
      - uses: actions/checkout@v4

      - name: Check requirements
        run: |
          set -x
          bun --version
          pnpm --version
          npm --version
          node --version
          node-gyp --version
          corepack --version
          yarn --version

      - name: Install, lint and check frontend
        run: |
          bun install
          bun run lint
          bun run oxlint
          bun run format:check


