name: NPM - Check source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: "Check CLI code - NPM"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node 24
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install, lint and check shared
        working-directory: shared
        run: | 
          npm install
          npm run lint
          npm run format:check

      - name: Install, lint and check backend
        working-directory: backend
        run: |
          npm install
          npm run lint
          npm run format:check

      - name: Install, lint and check frontend
        working-directory: frontend
        run: |
          npm install
          npm run lint
          npm run format:check


